### ISSUE TITLE
[메인페이지] 1차 UI 구현

### ISSUE THREAD

**Issue by y5037** [y5037/Rolling#10]
반응형으로 화면을 구현해주세요.

**Comment by ghkjiop92** [comment]
12/12~12/17

**Comment by ghkjiop92** [comment]
12.17 Rolling 메인 UI 페이지 작업시작

**Comment by ghkjiop92** [comment]
12.17

진행할 내용: 디자인 시안 맞춰서 사이즈 꾸미기 작업

**Comment by ghkjiop92** [comment]
12.18

진행한 내용: 디자인 시안 맞춰서 사이즈 맞추기

진행할 내용:반응형웹 적용하기

**Comment by ghkjiop92** [comment]
12.19
진행한 내용: pc 버전 디자인 시안 맞추기

진행할 내용: 태블릿 버전과 모바일 버전 미디어쿼리로 구현

**Comment by ghkjiop92** [comment]
12.20
진행한 내용: 태블릿 버전 미디어쿼리로 구현

진행할 내용: 모바일 버전구현 과 태블릿 버전 디자인 시안으로 맞추기

**Comment by ghkjiop92** [comment]
12.21 
진행한 내용: 태블릿 버전과 모바일 버전 미디어쿼리로 구현

진행할 내용: pc,태블릿, 모바일 디자인 시안으로 맞추기

**Comment by ghkjiop92** [comment]
12.22

진행한 내용: 최종 마무리 작업까지 끝내고 추가 수정요청은 상석님이 작업

**Comment by ghkjiop92** [comment]
12.23
진행한내용: 마무리 작업 한것 push하고, 인건님 merge 시킨것 확인후 , 다시 feature/mainPage 브랜치 삭제

**Comment by y5037** [comment]
메인페이지 1차 UI 작업 완료
