### ISSUE TITLE
[공통 Component] 공통 modal 및 badge 컴포넌트 생성

### ISSUE THREAD

**Issue by y5037** [y5037/Rolling#16]

**Comment by ghkjiop92** [comment]
Start Date:12/16~ End Date:12/18

**Comment by y5037** [comment]
12.13 Badge 컴포넌트 작업 시작 _동우님

**Comment by y5037** [comment]
12.13 Badge 컴포넌트 1차 작업 완료 _동우님

**Comment by y5037** [comment]
12.13 Badge 컴포넌트 2차 작업 (공통 컴포넌트 재사용성 관련 코드 추가) 완료 _혜림님

특이사항 : 해당 컴포넌트 사용법은 파일 내에 주석으로 달아놓았습니다.

**Comment by ghkjiop92** [comment]
12.13 Modal 컴포넌트 작업 시작 _동우님 
특이사항: 디자인 시안대로 작업 완수 어려워 컴펌 받기

**Comment by ghkjiop92** [comment]
Modal 1차 작업 완료 했고, 혜림님께 작업 요청 합니다.

**Comment by y5037** [comment]
12.14 Modal 2차 작업 시작

**Comment by y5037** [comment]
12.14 Modal 2차 작업 완료
