### ISSUE TITLE
[이모지 생성 ] 이모지 더블클릭시 데이터 무작위로 불러오는 문제 

### ISSUE THREAD

**Issue by ghkjiop92** [y5037/Rolling#192]
1.현재 좋아요 기능이 중복 클릭 시 데이터를 무작위로 불러오는 문제가 있음
2.좋아요 수가 아이디 당 1씩만 증가하고 감소하지 않는 기능적 제한이 있음
3.UI가 일부 환경(맥북)에서 캐시로 인해 깨지는 현상 발생

**Comment by y5037** [comment]
1. 토큰이 정상적으로 발행되면 한 토큰 당 1 카운트씩만 올리고 내릴 수 있게 개발할 수 있으며, 현재 API로써는 추가 구현이 불필요한 기능입니다.
2. 1번과 같은 내용입니다.
3. 확인이 필요합니다.
