### ISSUE TITLE
[롤링페이퍼 페이지 - Body] '롤링페이퍼 삭제하기' 버튼 클릭 시 페이지 이동

### ISSUE THREAD

**Issue by y5037** [y5037/Rolling#39]
롤링페이퍼 삭제하기를 누르면 해당 롤링페이퍼 페이지와 메세지들이 삭제 되고 롤링페이퍼 목록 페이지(/list)로 이동합니다.

**Comment by pss7** [comment]
Start Date : 2024-12-14
End Date : 2024-12-15
