### ISSUE TITLE
[공통 컴포넌트] 공통 토스트 컴포넌트 생성

### ISSUE THREAD

**Issue by y5037** [y5037/Rolling#91]
피그마 디자인대로 만들어주세요.

**Comment by ghkjiop92** [comment]
12.14 토스트 컴포넌트 작업 시작!!

**Comment by ghkjiop92** [comment]
git origin push 하고 머지된상태 
인건님이나 혜림님께 컴펌받는다.

**Comment by y5037** [comment]
12.15 머지 완료

12.15 디자인 시안에 조금 더 근접한 UI로 만들기 위한 마무리 CSS 작업을 완료하였습니다.
